### ISSUE TITLE
Questions about EWP host / connector

### ISSUE THREAD

**Issue by johannwilfling** [erasmus-without-paper/ewp-reference-connector#12]
Dear EWP team,

 we have some questions for a better understanding regarding the EWP host, the connectors and the HEIs.
 
 * Is the connector a technical implementation of an EWP host?
 
 * What has an individual HEI to implement to exchange data with the EWP host / connector.
 
Kind regards.

**Comment by wrygiel** [comment]
I suspect that your questions are for reference connector's authors, but since nobody is responding, I'll try to ;)

> Is the connector a technical implementation of an EWP host?

* As far as I can tell, the term "connector" is not clearly defined. It's more of a business term, which have been initially used in the EU grant proposal.
* An "EWP Host" is a more detailed technical term which usually describes one server and/or one client (but it can also describe many clients, or just a subset of server methods).
* The "reference connector" is an example implementation of EWP server and client (described by a single EWP Host) - you will not use it in your actual implementation, but you can browse through the code and see how it has been implemented by one of the teams.

> What has an individual HEI to implement to exchange data with the EWP host / connector.

It depends on what kind of data you want to exchange. For example:

* If you want to fetch data on institutions in the EWP Network, then you implement the manifest, and a client which connects to existing Institution APIs.
* If you also want to **publish** data on your own institution, then you also need to implement your own Institution API (the server part).
* Ideally, you will implement a server and the client for [each of the APIs](https://developers.erasmuswithoutpaper.eu/). But that's a huge amount of work, so you will do it in smaller steps.

A HEI which doesn't have any existing computer system, can also choose to not implement anything, and use an existing implementation provided by SOP in a cloud.
